# RBAC Configuration for LLMCluster Operator
#
# The operator needs permissions to:
# 1. Watch/list/get LLMCluster resources (the CRD we manage)
# 2. Create/update/delete StatefulSets, Deployments, Services, ConfigMaps
# 3. Create/update/delete HPAs, PDBs, NetworkPolicies
# 4. Read/write Status on LLMCluster resources

---
# ServiceAccount for the operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llmcluster-operator
  namespace: default
  labels:
    app: llmcluster-operator

---
# Role with permissions needed by the operator
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: llmcluster-operator
  namespace: default
  labels:
    app: llmcluster-operator
rules:
# ============================================
# CRD Permissions
# ============================================
# Get, List, Watch the CRD we manage
- apiGroups: ["serving.ai"]
  resources: ["llmclusters"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Update status subresource
- apiGroups: ["serving.ai"]
  resources: ["llmclusters/status"]
  verbs: ["get", "update", "patch"]

# Update scale subresource
- apiGroups: ["serving.ai"]
  resources: ["llmclusters/scale"]
  verbs: ["get", "update", "patch"]

# ============================================
# Core Resources (create/manage children)
# ============================================
# StatefulSets for model pods
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Deployments for router, queue, monitoring
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Services for networking
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Endpoints for service discovery
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]

# ConfigMaps for configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Secrets for sensitive data (HF tokens, etc.)
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]

# PersistentVolumeClaims for model cache
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Pods for status checking
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

# Events for recording events
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]

# ============================================
# Scaling
# ============================================
# HorizontalPodAutoscalers
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# ============================================
# High Availability
# ============================================
# PodDisruptionBudgets
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# ============================================
# Networking
# ============================================
# Ingress
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# NetworkPolicy
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# ============================================
# Monitoring (if enabled)
# ============================================
# ServiceMonitor for Prometheus Operator
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# PrometheusRule for alerting
- apiGroups: ["monitoring.coreos.com"]
  resources: ["prometheusrules"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
# RoleBinding to bind the Role to the ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: llmcluster-operator
  namespace: default
  labels:
    app: llmcluster-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: llmcluster-operator
subjects:
- kind: ServiceAccount
  name: llmcluster-operator
  namespace: default

---
# For cluster-wide resources, use ClusterRole/ClusterRoleBinding
# This is needed if the operator manages resources across namespaces
# or needs cluster-wide permissions (e.g., for CustomResourceDefinitions)

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: llmcluster-operator
  labels:
    app: llmcluster-operator
rules:
# CRD definitions (if operator creates CRDs dynamically)
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]

# Nodes (for GPU-aware scheduling decisions)
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]

# PersistentVolumes
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: llmcluster-operator
  labels:
    app: llmcluster-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: llmcluster-operator
subjects:
- kind: ServiceAccount
  name: llmcluster-operator
  namespace: default

# RBAC Hierarchy:
#
# ┌─────────────────────────────────────────────────────────────────┐
# │  ServiceAccount: llmcluster-operator                            │
# │  ┌───────────────────────────────────────────────────────────┐ │
# │  │  Role (namespace-scoped)                                  │ │
# │  │  - serving.ai/llmclusters (CRUD)                          │ │
# │  │  - apps/statefulsets (CRUD)                               │ │
# │  │  - apps/deployments (CRUD)                                │ │
# │  │  - core/services (CRUD)                                   │ │
# │  │  - core/configmaps (CRUD)                                 │ │
# │  │  - policy/poddisruptionbudgets (CRUD)                     │ │
# │  │  - autoscaling/hpas (CRUD)                                │ │
# │  │  └──> Bound by RoleBinding (namespace: default)          │ │
# │  └───────────────────────────────────────────────────────────┘ │
# │  ┌───────────────────────────────────────────────────────────┐ │
# │  │  ClusterRole (cluster-scoped)                             │ │
# │  │  - core/nodes (read-only)                                 │ │
# │  │  - core/persistentvolumes (read-only)                     │ │
# │  │  └──> Bound by ClusterRoleBinding                        │ │
# │  └───────────────────────────────────────────────────────────┘ │
# └─────────────────────────────────────────────────────────────────┘
