# NodePort Service
#
# A NodePort service exposes the service on each node's IP at a static port.
# Allows external access to the service via <NodeIP>:<NodePort>
#
# Key concepts:
# - NodePort: External access via node IP + port (30000-32767)
# - ClusterIP: NodePort also creates a ClusterIP for internal access
# - Port mapping: nodePort -> port -> targetPort
# - External access: Works from outside the cluster
#
# For LLM serving:
# - Use NodePort for development/testing external access
# - Production: Use LoadBalancer or Ingress instead
#
# Usage:
#   kubectl apply -f 02-nodeport.yaml
#   # Access via: curl http://<minikube-ip>:30080
#   kubectl delete -f 02-nodeport.yaml

---
# Deployment to test the service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nodeport
  labels:
    app: nginx
    service-type: nodeport
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        service-type: nodeport
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi

---
# NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  labels:
    app: nginx
    service-type: nodeport
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: http
    port: 80        # Service port (ClusterIP)
    targetPort: 80  # Container port
    nodePort: 30080 # Node port (external access, 30000-32767)
    protocol: TCP

# Results:
# - Service accessible via <NodeIP>:30080 from outside
# - Also has ClusterIP for internal access
# - Port mapping: NodeIP:30080 -> ClusterIP:80 -> PodIP:80
# - Works on ALL nodes (not just where pods are running)
