# Secret (Basic)
#
# A Secret stores sensitive data such as passwords, tokens, and keys.
# Similar to ConfigMap but for confidential data.
#
# Key concepts:
# - Secret: Store sensitive data (base64 encoded by default)
# - Security: Secrets are encoded, not encrypted (use KMS for encryption)
# - Usage: Environment variables, volume mounts, image pull secrets
#
# For LLM serving:
# - API keys (OpenAI, Anthropic, HuggingFace)
# - Database credentials
# - Model API tokens
# - TLS certificates
#
# Usage:
#   kubectl apply -f 03-secret.yaml
#   kubectl delete -f 03-secret.yaml

---
# Secret with sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: api-keys
  labels:
    app: llm-serving
type: Opaque  # Default type for arbitrary secrets
data:
  # Values must be base64 encoded
  # To encode: echo -n "my-api-key" | base64
  openai.api.key: b3BlbmFpLWFwaS1rZXkK # base64 for "openai-api-key"
  huggingface.token: aGZfdG9rZW4xMjM= # base64 for "hf_token123"
  database.password: cGFzc3dvcmQxMjM= # base64 for "password123"

---
# Pod using Secret as environment variables
apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
  labels:
    app: secret-demo
spec:
  containers:
  - name: demo
    image: nginx:1.25
    ports:
    - containerPort: 80
    env:
    # Reference Secret keys
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: api-keys
          key: openai.api.key
    - name: HUGGINGFACE_TOKEN
      valueFrom:
        secretKeyRef:
          name: api-keys
          key: huggingface.token
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: api-keys
          key: database.password
    resources:
      requests:
        cpu: 100m
        memory: 128Mi

# Security Notes:
# - Secret data is base64 encoded, NOT encrypted
# - Use Kubernetes Secrets encryption at rest (EncryptionConfiguration)
# - Consider external secret stores (Vault, AWS Secrets Manager)
# - Don't commit secrets to git
# - Use .gitignore for secret files
# - Consider Sealed Secrets or External Secrets Operator for production

# Best Practices:
# 1. Use RBAC to control secret access
# 2. Enable encryption at rest
# 3. Use separate namespaces for different environments
# 4. Rotate secrets regularly
# 5. Use external secret management for production
